// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/sso/v1/sso.proto

package ssov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_sso_v1_sso_proto protoreflect.FileDescriptor

const file_api_sso_v1_sso_proto_rawDesc = "" +
	"\n" +
	"\x14api/sso/v1/sso.proto\x123github.easymymind.mpm_sso_proto.protobuf.api.sso.v1\x1a\x19api/sso/v1/messages.proto2\xdc\x04\n" +
	"\x04Auth\x12\x97\x01\n" +
	"\bRegister\x12D.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterRequest\x1aE.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterResponse\x12\x8e\x01\n" +
	"\x05Login\x12A.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginRequest\x1aB.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginResponse\x12\x94\x01\n" +
	"\aIsAdmin\x12C.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminRequest\x1aD.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminResponse\x12\x91\x01\n" +
	"\x06Logout\x12B.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutRequest\x1aC.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutResponseB\xea\x02\n" +
	"7com.github.easymymind.mpm_sso_proto.protobuf.api.sso.v1B\bSsoProtoP\x01Z8github.com/easymymind/mpm_sso_proto/pkg/api/sso/v1;ssov1\xa2\x02\x06GEMPAS\xaa\x021Github.Easymymind.MpmSsoProto.Protobuf.Api.Sso.V1\xca\x021Github\\Easymymind\\MpmSsoProto\\Protobuf\\Api\\Sso\\V1\xe2\x02=Github\\Easymymind\\MpmSsoProto\\Protobuf\\Api\\Sso\\V1\\GPBMetadata\xea\x027Github::Easymymind::MpmSsoProto::Protobuf::Api::Sso::V1b\x06proto3"

var file_api_sso_v1_sso_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginRequest
	(*IsAdminRequest)(nil),   // 2: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminRequest
	(*LogoutRequest)(nil),    // 3: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutRequest
	(*RegisterResponse)(nil), // 4: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterResponse
	(*LoginResponse)(nil),    // 5: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginResponse
	(*IsAdminResponse)(nil),  // 6: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminResponse
	(*LogoutResponse)(nil),   // 7: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutResponse
}
var file_api_sso_v1_sso_proto_depIdxs = []int32{
	0, // 0: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Register:input_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterRequest
	1, // 1: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Login:input_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginRequest
	2, // 2: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.IsAdmin:input_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminRequest
	3, // 3: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Logout:input_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutRequest
	4, // 4: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Register:output_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.RegisterResponse
	5, // 5: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Login:output_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LoginResponse
	6, // 6: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.IsAdmin:output_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.IsAdminResponse
	7, // 7: github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.Auth.Logout:output_type -> github.easymymind.mpm_sso_proto.protobuf.api.sso.v1.LogoutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_sso_v1_sso_proto_init() }
func file_api_sso_v1_sso_proto_init() {
	if File_api_sso_v1_sso_proto != nil {
		return
	}
	file_api_sso_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sso_v1_sso_proto_rawDesc), len(file_api_sso_v1_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sso_v1_sso_proto_goTypes,
		DependencyIndexes: file_api_sso_v1_sso_proto_depIdxs,
	}.Build()
	File_api_sso_v1_sso_proto = out.File
	file_api_sso_v1_sso_proto_goTypes = nil
	file_api_sso_v1_sso_proto_depIdxs = nil
}
